################################################################################
# Test file for HTTP routes of the API
# Needs REST Client VSCode addon
# https://marketplace.visualstudio.com/items?itemName=humao.rest-client
################################################################################

@endpoint = http://localhost:{{$dotenv PORT}}/api

### 404
GET {{ endpoint }}/ofkjshsekih

#########################
#        SENTENCE       #
#########################

### Get random sentence (except 1)
GET {{ endpoint }}/sentence
### Get first sentence

GET {{ endpoint }}/sentence/first

#########################
#     PLAYER ACCOUNT    #
#########################

### Get player account infos
GET {{ endpoint }}/playerAccount/2

### Get wrong player account infos
GET {{ endpoint }}/playerAccount/57

### Insert player account
POST {{ endpoint }}/playerAccount/
content-type: application/json

{
    "username": "playerrrr",
    "mail": "player@player.com",
    "password": "azerty",
    "passwordConfirm": "azerty"
}

### Insert wrong player account
POST {{ endpoint }}/playerAccount/
content-type: application/json

{
    "username": "playeskejrhzkerhr",
    "mail": "player@player.com",
    "password": "azerty",
    "passwordConfirm": "azerty"
}
